  version: 1.0
  workflows:
    - subclass: WDL
      primaryDescriptorPath: /PharmCAP_Pipeline.wdl
      name: PharmCAP_Pipeline
      readMePath: /README.md
      testParameterFiles:
        - /parameters.json